services:
  postgis:
    image: postgis/postgis:13-3.1
    environment:
      POSTGRES_DB: guira
      POSTGRES_USER: guira
      POSTGRES_PASSWORD: guira_pass
    ports: ["5432:5432"]
    volumes:
      - postgis_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data
    ports: ["9000:9000"]
    volumes: ["minio_data:/data"]

  redis:
    image: redis:7
    ports: ["6379:6379"]

volumes:
  postgis_data:
  minio_data: