name: fire-prevention
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - pip:
    - ultralytics
    - timm
    - transformers
    - deepforest
    - rasterio
    - xarray
    - pandas
    - scikit-learn
    - jupyter
    - tensorboard
    - pyyaml
    - opencv-python-headless
